### ISSUE TITLE
Error trying to run.

### ISSUE THREAD

**Issue by shophk** [eschriek/rtmpdump-android#4]
Please help to see how I may resolve this, thanks!

02-02 17:00:04.168  15840-15840/com.schriek.rtmpdump I/SELinux﹕ Function: selinux_android_load_priority [0], There is no sepolicy file.
02-02 17:00:04.168  15840-15840/com.schriek.rtmpdump I/SELinux﹕ Function: selinux_android_load_priority [1], There is no sepolicy version file.
02-02 17:00:04.168  15840-15840/com.schriek.rtmpdump I/SELinux﹕ Function: selinux_android_load_priority , loading version is VE=SEPF_GT-I9505_4.4.2_0007
02-02 17:00:04.168  15840-15840/com.schriek.rtmpdump I/SELinux﹕ selinux_android_seapp_context_reload: seapp_contexts file is loaded from /seapp_contexts
02-02 17:00:04.188  15840-15840/com.schriek.rtmpdump D/dalvikvm﹕ Late-enabling CheckJNI
02-02 17:00:04.298  15840-15840/com.schriek.rtmpdump W/ApplicationPackageManager﹕ getCSCPackageItemText()
02-02 17:00:04.388  15840-15840/com.schriek.rtmpdump D/dalvikvm﹕ Trying to load lib /data/app-lib/com.schriek.rtmpdump-2/librtmpdump.so 0x42a0a640
02-02 17:00:04.388  15840-15840/com.schriek.rtmpdump E/dalvikvm﹕ dlopen("/data/app-lib/com.schriek.rtmpdump-2/librtmpdump.so") failed: dlopen failed: cannot locate symbol "signal" referenced by "librtmpdump.so"...
02-02 17:00:04.388  15840-15840/com.schriek.rtmpdump E/Rtmpdump﹕ dlopen failed: cannot locate symbol "signal" referenced by "librtmpdump.so"...
02-02 17:00:04.388  15840-15840/com.schriek.rtmpdump W/dalvikvm﹕ No implementation found for native Lcom/schriek/rtmpdump/Rtmpdump;.run:([Ljava/lang/String;)V
02-02 17:00:04.388  15840-15840/com.schriek.rtmpdump D/AndroidRuntime﹕ Shutting down VM
02-02 17:00:04.388  15840-15840/com.schriek.rtmpdump W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41809da0)
02-02 17:00:04.388  15840-15840/com.schriek.rtmpdump E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.schriek.rtmpdump, PID: 15840
    java.lang.UnsatisfiedLinkError: Native method not found: com.schriek.rtmpdump.Rtmpdump.run:([Ljava/lang/String;)V
            at com.schriek.rtmpdump.Rtmpdump.run(Native Method)
            at com.schriek.rtmpdump.Rtmpdump.parseString(Rtmpdump.java:18)
            at com.schriek.rtmpdump.LogFragment.onCreateView(LogFragment.java:42)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
            at android.view.View.measure(View.java:17387)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:17387)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
            at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
            at android.view.View.measure(View.java:17387)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2533)
            at android.view.View.measure(View.java:17387)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2211)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1350)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1547)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1234)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6465)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
            at android.view.Choreographer.doCallbacks(Choreographer.java:603)
            at android.view.Choreographer.doFrame(Choreographer.java:573)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by fabio-calisoft** [comment]
what version of Android are you running ?

signal was an inline function until platform android-21, now it's not inline anymore.

When you use the ndk r10, android-21 is used by default but it's not fully retro-compatible with devices running former Android versions. In your case, signal can't be found on your device (but it would run properly on Lollipop).

When using the NDK, you should use the platform (APP_PLATFORM:=android-XX) that corresponds to your android:minSdkVersion.

So here you can set APP_PLATFORM:=android-15 inside Application.mk Makefile, and your lib will use the inline version of signal, so it will not look for its symbol at runtime.

**Comment by shophk** [comment]
It did work on Lollipop but
I m using android version 4.4.2.
I have updated AndroidManifest to android:minSdkVersion="15"
In Gradle scripts I have updated to the following:
  android {
        compileSdkVersion = 23
        buildToolsVersion = "23.0.2"

```
    defaultConfig.with {
        applicationId = "com.schriek.rtmpdump"
        minSdkVersion.apiLevel = 15
        targetSdkVersion.apiLevel = 23
    }
}
```

Here is the error after the above changes. 
02-02 18:59:13.457  25285-25285/? I/SELinux﹕ Function: selinux_android_load_priority [0], There is no sepolicy file.
02-02 18:59:13.457  25285-25285/? I/SELinux﹕ Function: selinux_android_load_priority [1], There is no sepolicy version file.
02-02 18:59:13.457  25285-25285/? I/SELinux﹕ Function: selinux_android_load_priority , loading version is VE=SEPF_GT-I9505_4.4.2_0007
02-02 18:59:13.457  25285-25285/? I/SELinux﹕ selinux_android_seapp_context_reload: seapp_contexts file is loaded from /seapp_contexts
02-02 18:59:13.467  25285-25285/? D/dalvikvm﹕ Late-enabling CheckJNI
02-02 18:59:13.607  25285-25285/com.schriek.rtmpdump W/ApplicationPackageManager﹕ getCSCPackageItemText()
02-02 18:59:13.707  25285-25285/com.schriek.rtmpdump D/dalvikvm﹕ Trying to load lib /data/app-lib/com.schriek.rtmpdump-6/librtmpdump.so 0x42a0e3a8
02-02 18:59:13.707  25285-25285/com.schriek.rtmpdump E/dalvikvm﹕ dlopen("/data/app-lib/com.schriek.rtmpdump-6/librtmpdump.so") failed: dlopen failed: cannot locate symbol "signal" referenced by "librtmpdump.so"...
02-02 18:59:13.707  25285-25285/com.schriek.rtmpdump E/Rtmpdump﹕ dlopen failed: cannot locate symbol "signal" referenced by "librtmpdump.so"...
02-02 18:59:13.707  25285-25285/com.schriek.rtmpdump W/dalvikvm﹕ No implementation found for native Lcom/schriek/rtmpdump/Rtmpdump;.run:([Ljava/lang/String;)V
02-02 18:59:13.707  25285-25285/com.schriek.rtmpdump D/AndroidRuntime﹕ Shutting down VM
02-02 18:59:13.707  25285-25285/com.schriek.rtmpdump W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41809da0)
02-02 18:59:13.707  25285-25285/com.schriek.rtmpdump E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.schriek.rtmpdump, PID: 25285
    java.lang.UnsatisfiedLinkError: Native method not found: com.schriek.rtmpdump.Rtmpdump.run:([Ljava/lang/String;)V
            at com.schriek.rtmpdump.Rtmpdump.run(Native Method)
            at com.schriek.rtmpdump.Rtmpdump.parseString(Rtmpdump.java:18)
            at com.schriek.rtmpdump.LogFragment.onCreateView(LogFragment.java:42)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
            at android.view.View.measure(View.java:17387)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:17387)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
            at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
            at android.view.View.measure(View.java:17387)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2533)
            at android.view.View.measure(View.java:17387)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2211)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1350)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1547)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1234)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6465)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
            at android.view.Choreographer.doCallbacks(Choreographer.java:603)
            at android.view.Choreographer.doFrame(Choreographer.java:573)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by eschriek** [comment]
I have experienced issues like these before due to mismatching compile SDK version and target device SDK version, basically what @secure-digital-delivery explained.

Since you are targeting 4.4.2, try setting compile SDK version to 19.
